name       : libnma
version    : 1.8.32
release    : 8
source     :
    - https://download.gnome.org/sources/libnma/1.8/libnma-1.8.32.tar.xz : 0a57b93a2fad43acc763f320dd3a7a93c429b0e3118dfa549d67824cddc4e905
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Library for network-manager-applet
description: |
    Library for network-manager-applet
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(iso-codes)
    - pkgconfig(libnm)
    - pkgconfig(mobile-broadband-provider-info)
    - vala
rundeps    :
    - mobile-broadband-provider-info
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
