name       : libnma
version    : 1.10.2
release    : 11
source     :
    - https://download.gnome.org/sources/libnma/1.10/libnma-1.10.2.tar.xz : 4fc3d9c404b7b13303d9394f96961c5298d71afa9f1fa7af5e4f0f6e842a0940
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Library for network-manager-applet
description: |
    Library for network-manager-applet
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(gtk4)
    - pkgconfig(iso-codes)
    - pkgconfig(libnm)
    - pkgconfig(mobile-broadband-provider-info)
    - vala
rundeps    :
    - mobile-broadband-provider-info
setup      : |
    %meson_configure -Dgtk_doc=false -Dlibnma_gtk4=true
build      : |
    %ninja_build
install    : |
    %ninja_install
