name       : libnma
version    : 1.8.28
release    : 1
source     :
    - https://download.gnome.org/sources/libnma/1.8/libnma-1.8.28.tar.xz : 4af69552d131a3b2b8b6a2df584044258bf588448dcdb4bddfa12a07c134b726
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Library for network-manager-applet
description: |
    Library for network-manager-applet
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(iso-codes)
    - pkgconfig(libnm)
    - pkgconfig(mobile-broadband-provider-info)
    - vala
rundeps    :
    - mobile-broadband-provider-info
setup      : |
    %patch -p1 < $pkgfiles/version-calculate-NMA_API_VERSION-based-on-the-version-number.patch
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
