name       : libnma
version    : 1.8.30
release    : 3
source     :
    - https://download.gnome.org/sources/libnma/1.8/libnma-1.8.30.tar.xz : da33e72a49e07d855d97a52aa9a8962a4c96f52b9168c4e0027117ad8ffdafb4
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Library for network-manager-applet
description: |
    Library for network-manager-applet
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(iso-codes)
    - pkgconfig(libnm)
    - pkgconfig(mobile-broadband-provider-info)
    - vala
rundeps    :
    - mobile-broadband-provider-info
setup      : |
    %meson_configure -Dgtk_doc=false
build      : |
    %ninja_build
install    : |
    %ninja_install
